on:
  workflow_dispatch:

jobs:
  test:
    name: test install/run against example.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout your repository code
      
      - name: Make script executable
        run: chmod +x ./install.sh # Ensure your script has execute permissions
      
      - name: Make script executable
        run: chmod +x ./install.sh # Ensure your script has execute permissions
        
      - name: test install
        run: ./install.sh
        
      - name: test run
        run: ./run.sh -wd46 
